### ISSUE TITLE
submitfilter is broken if a Python module is loaded

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc-jobs#85]
This was reported in a user ticket, where one (preprocessing) job submits another (real work) job:

```
[vsc40003@gligar01 ~]$ ml Python/2.7.12-intel-2016b
[vsc40003@gligar01 ~]$ echo "echo hello" > t.sh
[vsc40003@gligar01 ~]$ qsub t.sh
Traceback (most recent call last):
  File "/usr/bin/submitfilter", line 40, in <module>
    from vsc.jobs.pbs.clusterdata import get_clusterdata, get_cluster_mpp, get_cluster_overhead, MASTER_REGEXP
ImportError: No module named vsc.jobs.pbs.clusterdata
qsub: submit filter returned an error code, aborting job submission.
```

Workaround for now is to run `module purge` before `qsub`, but we should get this fixed.

I'm not entirely sure *why* this happens though, since we have this:

```
head -1 /usr/bin/submitfilter 
#!/usr/bin/python -E
```

So, `$PYTHONPATH` is not the problem...

**Comment by boegel** [comment]
Some more info:

```
[vsc40003@gligar01 ~]$ echo $PYTHONPATH
/user/home/gent/vsc400/vsc40003/myeasyblocks:/user/home/gent/vsc400/vsc40003/easybuild_easyinstalled/lib/python2.6/site-packages:/user/home/gent/vsc400/vsc40003/easyblocks_ugent:

[vsc40003@gligar01 ~]$ ml
Currently Loaded Modules:
  1) cluster/delcatty            (S)   4) icc/2016.3.210-GCC-5.4.0-2.26        7) impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26  10) intel/2016b              13) libreadline/6.3-intel-2016b  16) SQLite/3.13.0-intel-2016b  19) libffi/3.2.1-intel-2016b
  2) GCCcore/5.4.0                     5) ifort/2016.3.210-GCC-5.4.0-2.26      8) iimpi/2016b                                        11) bzip2/1.0.6-intel-2016b  14) ncurses/6.0-intel-2016b      17) Tk/8.6.5-intel-2016b       20) Python/2.7.12-intel-2016b
  3) binutils/2.26-GCCcore-5.4.0       6) iccifort/2016.3.210-GCC-5.4.0-2.26   9) imkl/11.3.3.210-iimpi-2016b                        12) zlib/1.2.8-intel-2016b   15) Tcl/8.6.5-intel-2016b        18) GMP/6.1.1-intel-2016b

  Where:
   S:  Module is Sticky, requires --force to unload or purge

[vsc40003@gligar01 ~]$ which python
/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/bin/python
# ^ not the Python we're using in the submitfilter ^

# v still causes trouble, even though we're ignoring $PYTHONPATH v
[vsc40003@gligar01 ~]$ /usr/bin/python -E -c "import vsc"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named vsc

[vsc40003@gligar01 ~]$ /usr/bin/python -E -c "import sys; print sys.path"
['', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/setuptools-23.1.0-py2.7.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/blist-1.3.6-py2.7-linux-x86_64.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/Cython-0.24-py2.7-linux-x86_64.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/six-1.10.0-py2.7.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/python_dateutil-2.5.3-py2.7.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/decorator-4.0.10-py2.7.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/liac_arff-2.1.0-py2.7.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/ecdsa-0.13-py2.7.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/cryptography-1.4-py2.7-linux-x86_64.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/ipaddress-1.0.18-py2.7.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/enum34-1.1.6-py2.7.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/pyasn1-0.1.9-py2.7.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/idna-2.2-py2.7.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/paramiko-2.0.1-py2.7.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/pyparsing-2.1.5-py2.7.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/netifaces-0.10.4-py2.7-linux-x86_64.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/funcsigs-1.0.2-py2.7.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/pytz-2016.4-py2.7.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/pandas-0.18.1-py2.7-linux-x86_64.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/virtualenv-15.0.2-py2.7.egg', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python27.zip', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/plat-linux2', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/lib-tk', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/lib-old', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/lib-dynload', '/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages']
```

**Comment by JensTimmerman** [comment]
this is probably because python picks up the `/apps/gent/CO7/sandybridge/software/Python/2.7.12-intel-2016b/lib/libpython2.7.so` which then does things?

**Comment by boegel** [comment]
The only way to fix this imho is through a wrapper (bash) script `submitfilter` which calls `unset LD_LIBRARY_PATH; /usr/bin/python -E /path/to/submitfilter.py`.

There's no other way to avoid that `/usr/bin/python` picks up the wrong `libpython2.7.so`.

This is a new problem on the login nodes since SL6 had Python2.6 which goes looking for `libpython2.6.so` (and nobody loads a `Python/2.6-*` module that can screw this up).

**Comment by JensTimmerman** [comment]
will be fixed by https://github.com/hpcugent/vsc-jobs/pull/86#
